root: true
env:
  node: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaVersion: latest
plugins:
  - 'prettier'
rules:
  'prettier/prettier': 'warn'
overrides:
  - files:
      - '**/__tests__/*.{j,t}s?(x)'
      - '**/tests/unit/**/*.spec.{j,t}s?(x)'
    env:
      jest: true
